"use client";
import Icon from "@/components/wrappers/Icon";
import { useSettingsContext } from "@/context/useSettingsContext";
import React, { useCallback, useEffect, useMemo, useState } from "react";
import {
  Alert,
  Badge,
  Button,
  Card,
  CardBody,
  Col,
  FormCheck,
  FormControl,
  FormLabel,
  FormSelect,
  OverlayTrigger,
  Row,
  Spinner,
  Tooltip,
} from "react-bootstrap";
import toast from "react-hot-toast";
import { initialWebsiteSettings, WebsiteSettingItem } from "../../dataStore";
import { usePageAccess } from "@/hooks/useAccess";

const API_URL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:5000/api";

const WebsiteSettingsContent = () => {
  const { write: canWrite, delete: canDelete } = usePageAccess("Settings");
  const { updateSettingsCache } = useSettingsContext();
  const [settings, setSettings] = useState<WebsiteSettingItem[]>(
    initialWebsiteSettings,
  );
  const [activeGroup, setActiveGroup] = useState<string>("General");
  const [isAdding, setIsAdding] = useState<boolean>(false);
  const [saveMessage, setSaveMessage] = useState<string>("");

  // Node API connection state
  const [isLoading, setIsLoading] = useState<boolean>(true);
  const [apiConnected, setApiConnected] = useState<boolean>(false);
  const [apiStatusMessage, setApiStatusMessage] = useState<string>(
    "Connecting to Node API...",
  );

  // Add new form state
  const [newSetting, setNewSetting] = useState({
    displayName: "",
    key: "",
    type: "text" as "text" | "file" | "textarea" | "switch" | "",
    group: "General",
    value: "",
  });
  const [isKeyAutoGenerated, setIsKeyAutoGenerated] = useState<boolean>(true);

  const generateAutoKey = (displayName: string, grp: string) => {
    const cleanName = displayName.trim();
    if (!cleanName) return "";
    const slug = cleanName
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "_")
      .replace(/^_|_$/g, "");
    const groupSlug = (grp.trim() || "general")
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "_")
      .replace(/^_|_$/g, "");
    return slug ? `${groupSlug}.${slug}` : "";
  };

  // Form validation errors state
  const [errors, setErrors] = useState<{
    displayName?: string;
    key?: string;
    type?: string;
    group?: string;
  }>({});

  // Searchable & Creatable group dropdown state
  const [groupSearch, setGroupSearch] = useState<string>("General");
  const [showGroupDropdown, setShowGroupDropdown] = useState<boolean>(false);

  // Fetch dynamic settings from Node API
  const fetchSettingsFromApi = useCallback(async () => {
    setIsLoading(true);
    try {
      const token =
        typeof window !== "undefined"
          ? localStorage.getItem("token") || sessionStorage.getItem("token")
          : null;
      const headers: HeadersInit = token
        ? { Authorization: `Bearer ${token}` }
        : {};

      // Try primary admin endpoint first, fallback to general settings endpoint if needed
      let response = await fetch(`${API_URL}/admin/settings`, { headers });
      if (!response.ok) {
        response = await fetch(`${API_URL}/settings`, { headers });
      }

      if (response.ok) {
        const result = await response.json();
        const fetchedItems = Array.isArray(result.data)
          ? result.data
          : Array.isArray(result)
            ? result
            : initialWebsiteSettings;
        const cleanedItems = fetchedItems.map((s: WebsiteSettingItem) => {
          const cleanKey = s.key
            ? String(s.key)
                .trim()
                .replace(/^setting\(['"](.+)['"]\)$/, "$1")
            : "";
          
          const initMatch = initialWebsiteSettings.find(init => init.key === cleanKey);

          return {
            ...initMatch,
            ...s,
            key: cleanKey,
            type: initMatch ? initMatch.type : (s.type || "text"),
            previewUrl: s.previewUrl || s.value || (initMatch ? initMatch.previewUrl : ""),
          };
        });
        setSettings(cleanedItems);
        setApiConnected(true);
        setApiStatusMessage(`Connected to API (${API_URL})`);
      } else {
        throw new Error("API response was not OK");
      }
    } catch (err: any) {
      console.warn(
        "Server offline or unreachable. Using initial state fallback:",
        err,
      );
      setSettings(initialWebsiteSettings);
      setApiConnected(false);
      setApiStatusMessage("Server offline (using local fallback state)");
    } finally {
      setIsLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchSettingsFromApi();
  }, [fetchSettingsFromApi]);

  // Sync settings with global cache and document title
  useEffect(() => {
    if (settings && settings.length > 0) {
      updateSettingsCache(settings);
    }
  }, [settings, updateSettingsCache]);

  // Extract unique groups
  const groups = useMemo(() => {
    const set = new Set<string>();
    settings.forEach((s) => set.add(s.group));
    return Array.from(set);
  }, [settings]);

  const matchingGroups = useMemo(() => {
    if (!groupSearch.trim()) return groups;
    return groups.filter((g) =>
      g.toLowerCase().includes(groupSearch.toLowerCase()),
    );
  }, [groups, groupSearch]);

  const exactGroupMatch = useMemo(() => {
    return groups.some(
      (g) => g.toLowerCase() === groupSearch.trim().toLowerCase(),
    );
  }, [groups, groupSearch]);

  const filteredSettings = useMemo(() => {
    if (activeGroup === "All") return settings;
    return settings.filter((s) => s.group === activeGroup);
  }, [settings, activeGroup]);

  const handleUpdateValue = async (id: string, newValue: any) => {
    // Optimistic UI update
    setSettings((prev) =>
      prev.map((s) =>
        s.id === id
          ? {
              ...s,
              value: newValue,
              ...(s.type === "file" ? { previewUrl: newValue } : {}),
            }
          : s,
      ),
    );

    const token =
      typeof window !== "undefined"
        ? localStorage.getItem("token") || sessionStorage.getItem("token")
        : null;
    const headers: HeadersInit = {
      "Content-Type": "application/json",
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
    };

    try {
      let res = await fetch(`${API_URL}/admin/settings/${id}`, {
        method: "PUT",
        headers,
        body: JSON.stringify({ value: newValue, previewUrl: newValue }),
      });
      if (!res.ok) {
        await fetch(`${API_URL}/settings/${id}`, {
          method: "PUT",
          headers,
          body: JSON.stringify({ value: newValue, previewUrl: newValue }),
        });
      }
    } catch (err) {
      console.warn("Failed updating setting value", err);
    }
  };

  const handleFileUpload = async (
    id: string,
    event: React.ChangeEvent<HTMLInputElement>,
  ) => {
    const file = event.target.files?.[0];
    if (!file) return;

    const localUrl = URL.createObjectURL(file);
    setSettings((prev) =>
      prev.map((s) =>
        s.id === id
          ? { ...s, value: localUrl, previewUrl: localUrl }
          : s,
      ),
    );

    const formData = new FormData();
    formData.append("file", file);

    const token =
      typeof window !== "undefined"
        ? localStorage.getItem("token") || sessionStorage.getItem("token")
        : null;
    const headers: HeadersInit = token
      ? { Authorization: `Bearer ${token}` }
      : {};

    try {
      // Upload directly to the Next.js server to ensure images are saved in the frontend's public/images directory
      let response = await fetch(`/local-api/upload`, {
        method: "POST",
        body: formData,
      });
      if (response.ok) {
        const resData = await response.json();
        const uploadedUrl =
          resData.url || (resData.data && resData.data.url) || "";
        if (uploadedUrl) {
          await handleUpdateValue(id, uploadedUrl);
          toast.success(
            "File uploaded and applied to website settings successfully!",
          );
          setSaveMessage("File uploaded and applied across settings!");
          setTimeout(() => setSaveMessage(""), 3500);
          return;
        }
      }
      toast.success("File attached (local state fallback)");
    } catch (err) {
      console.warn("File upload offline/fallback:", err);
      toast.success("File attached (local fallback state)");
    }
  };

  const handleUpdateGroup = async (id: string, newGroup: string) => {
    // Optimistic UI update
    setSettings((prev) =>
      prev.map((s) => (s.id === id ? { ...s, group: newGroup } : s)),
    );

    const token =
      typeof window !== "undefined"
        ? localStorage.getItem("token") || sessionStorage.getItem("token")
        : null;
    const headers: HeadersInit = {
      "Content-Type": "application/json",
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
    };

    try {
      let res = await fetch(`${API_URL}/admin/settings/${id}`, {
        method: "PUT",
        headers,
        body: JSON.stringify({ group: newGroup }),
      });
      if (!res.ok) {
        await fetch(`${API_URL}/settings/${id}`, {
          method: "PUT",
          headers,
          body: JSON.stringify({ group: newGroup }),
        });
      }
    } catch (err) {
      console.warn("Failed updating setting group dynamically", err);
    }
  };

  const handleDeleteSetting = async (id: string) => {
    const itemToDelete = settings.find((s) => s.id === id);
    setSettings((prev) => prev.filter((s) => s.id !== id));

    const token =
      typeof window !== "undefined"
        ? localStorage.getItem("token") || sessionStorage.getItem("token")
        : null;
    const headers: HeadersInit = token
      ? { Authorization: `Bearer ${token}` }
      : {};

    try {
      let res = await fetch(`${API_URL}/admin/settings/${id}`, {
        method: "DELETE",
        headers,
      });
      if (!res.ok) {
        res = await fetch(`${API_URL}/settings/${id}`, {
          method: "DELETE",
          headers,
        });
      }
      if (res.ok) {
        toast.success(
          `Setting "${itemToDelete?.displayName || id}" deleted successfully!`,
        );
      } else {
        toast.success(`Setting deleted (local fallback)`);
      }
    } catch (err) {
      toast.success(`Setting deleted (local fallback)`);
    }
  };

  const handleAddSetting = async (e: React.FormEvent) => {
    e.preventDefault();

    // Validate required fields
    const newErrors: typeof errors = {};

    if (!newSetting.displayName.trim()) {
      newErrors.displayName = "Display Name is required.";
    }
    if (!newSetting.key.trim()) {
      newErrors.key = "Setting Key is required.";
    }
    if (!newSetting.type) {
      newErrors.type = "Please select a Setting Type.";
    }
    const finalGroup = groupSearch.trim() || newSetting.group;
    if (!finalGroup) {
      newErrors.group = "Group is required. Select or enter a group.";
    }

    if (Object.keys(newErrors).length > 0) {
      setErrors(newErrors);
      return;
    }

    setErrors({});

    const groupSlug =
      (finalGroup || "general")
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "_")
        .replace(/^_|_$/g, "") || "general";
    const rawKey =
      newSetting.key.trim() ||
      newSetting.displayName
        .trim()
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "_")
        .replace(/^_|_$/g, "");

    const unwrappedRaw = rawKey.replace(/^setting\(['"](.+)['"]\)$/, "$1");
    const cleanKey = unwrappedRaw
      .toLowerCase()
      .replace(/[^a-z0-9._]+/g, "_")
      .replace(/^_|_$/g, "");
    const formattedKey = cleanKey.includes(".")
      ? cleanKey
      : `${groupSlug}.${cleanKey}`;

    const addedItem: WebsiteSettingItem = {
      id: `SET-${Date.now()}`,
      displayName: newSetting.displayName.trim(),
      key: formattedKey,
      type: newSetting.type as "text" | "file" | "textarea" | "switch",
      group: finalGroup,
      value: newSetting.type === "switch" ? false : newSetting.value || "",
    };

    // Optimistic UI update
    setSettings((prev) => [addedItem, ...prev]);
    setActiveGroup(finalGroup);
    setNewSetting({
      displayName: "",
      key: "",
      type: "text",
      group: finalGroup,
      value: "",
    });
    setIsKeyAutoGenerated(true);
    setGroupSearch(finalGroup);
    setIsAdding(false);

    // Send to Node API
    const token =
      typeof window !== "undefined"
        ? localStorage.getItem("token") || sessionStorage.getItem("token")
        : null;
    const headers: HeadersInit = {
      "Content-Type": "application/json",
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
    };

    try {
      let res = await fetch(`${API_URL}/admin/settings`, {
        method: "POST",
        headers,
        body: JSON.stringify(addedItem),
      });
      if (!res.ok) {
        res = await fetch(`${API_URL}/settings`, {
          method: "POST",
          headers,
          body: JSON.stringify(addedItem),
        });
      }
      if (res.ok) {
        const result = await res.json();
        const createdItem = result.data || result;
        if (createdItem && createdItem.id) {
          setSettings((prev) =>
            prev.map((s) =>
              s.id === addedItem.id ? { ...s, ...createdItem } : s,
            ),
          );
        }
        toast.success(`Setting "${addedItem.displayName}" saved successfully!`);
        setSaveMessage(
          `Setting "${addedItem.displayName}" saved successfully under "${finalGroup}"!`,
        );
      } else {
        toast.success(`Setting "${addedItem.displayName}" added (local state)`);
        setSaveMessage(
          `Setting "${addedItem.displayName}" added (local state fallback)`,
        );
      }
    } catch (err) {
      toast.success(
        `Setting "${addedItem.displayName}" added (local fallback)`,
      );
      setSaveMessage(
        `Setting "${addedItem.displayName}" added (local state fallback)`,
      );
    }
    setTimeout(() => setSaveMessage(""), 3500);
  };

  const handleSelectGroupOption = (grp: string) => {
    const autoKey = isKeyAutoGenerated
      ? generateAutoKey(newSetting.displayName, grp)
      : newSetting.key;
    setNewSetting((prev) => ({ ...prev, group: grp, key: autoKey }));
    setGroupSearch(grp);
    if (errors.group) setErrors((prev) => ({ ...prev, group: undefined }));
    if (isKeyAutoGenerated && errors.key)
      setErrors((prev) => ({ ...prev, key: undefined }));
    setShowGroupDropdown(false);
  };

  const handleSaveAll = async () => {
    const token =
      typeof window !== "undefined"
        ? localStorage.getItem("token") || sessionStorage.getItem("token")
        : null;
    const headers: HeadersInit = {
      "Content-Type": "application/json",
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
    };

    try {
      let res = await fetch(`${API_URL}/admin/settings/bulk-save`, {
        method: "POST",
        headers,
        body: JSON.stringify({ settings }),
      });
      if (!res.ok) {
        res = await fetch(`${API_URL}/settings/bulk-save`, {
          method: "POST",
          headers,
          body: JSON.stringify({ settings }),
        });
      }
      if (res.ok) {
        toast.success("All website settings saved successfully!");
        setSaveMessage("All website settings saved successfully!");
      } else {
        toast.success("All settings saved locally!");
        setSaveMessage("All website settings saved successfully!");
      }
    } catch (err) {
      toast.success("All settings saved locally!");
      setSaveMessage("All website settings saved successfully!");
    }
    setTimeout(() => setSaveMessage(""), 3000);
  };

  return (
    <div className="website-settings-module">
      {/* Dynamic API Connection Indicator */}
      <div className="d-flex align-items-center justify-content-between flex-wrap gap-2 mb-3 bg-light p-2 px-3 rounded-3 border">
        <div className="d-flex align-items-center gap-2">
          <Badge
            bg={apiConnected ? "success" : "warning"}
            className="px-3 py-1 fs-12 fw-medium rounded-pill d-inline-flex align-items-center gap-1"
          >
            <Icon
              icon={apiConnected ? "check-circle" : "alert-circle"}
              className="fs-14"
            />
            <span>Node API Status: {apiStatusMessage}</span>
          </Badge>
          {isLoading && (
            <div className="d-flex align-items-center gap-2 text-primary fs-12 fw-semibold">
              <Spinner animation="border" size="sm" />
              <span>Fetching from Node API...</span>
            </div>
          )}
        </div>
        <Button
          variant="outline-primary"
          size="sm"
          className="d-flex align-items-center gap-1 fs-12 px-2 py-1"
          onClick={() => fetchSettingsFromApi()}
          disabled={isLoading}
        >
          <Icon
            icon="refresh-cw"
            className={`fs-13 ${isLoading ? "spinner-border spinner-border-sm border-0" : ""}`}
          />
          <span>Refresh API</span>
        </Button>
      </div>

      {saveMessage && (
        <Alert
          variant="success"
          className="d-flex align-items-center gap-2 mb-3"
          onClose={() => setSaveMessage("")}
          dismissible
        >
          <Icon icon="check-circle" className="fs-18 flex-shrink-0" />
          <span>{saveMessage}</span>
        </Alert>
      )}

      {/* Top Controls Bar matching Image 1 & 2 */}
      <div className="d-flex flex-wrap align-items-center justify-content-between gap-3 mb-4 pb-3 border-bottom">
        <div className="d-flex flex-wrap align-items-center gap-2">
          {groups.map((grp) => (
            <Button
              key={grp}
              variant={activeGroup === grp && !isAdding ? "primary" : "light"}
              size="sm"
              className="px-3 py-2 fw-semibold rounded-2"
              onClick={() => {
                setActiveGroup(grp);
                setIsAdding(false);
              }}
            >
              {grp}
            </Button>
          ))}
          <Button
            variant={activeGroup === "All" && !isAdding ? "primary" : "light"}
            size="sm"
            className="px-3 py-2 fw-semibold rounded-2"
            onClick={() => {
              setActiveGroup("All");
              setIsAdding(false);
            }}
          >
            All Groups
          </Button>

          {canWrite && (
            <Button
              variant={isAdding ? "primary" : "light"}
              size="sm"
              className="px-3 py-2 fw-semibold rounded-2 d-flex align-items-center gap-1 ms-1"
              onClick={() => {
                if (!isAdding) {
                  const grp = activeGroup !== "All" ? activeGroup : "General";
                  setNewSetting((prev) => ({ ...prev, group: grp }));
                  setIsKeyAutoGenerated(true);
                  setGroupSearch(grp);
                  setErrors({});
                }
                setIsAdding(!isAdding);
              }}
            >
              <Icon icon="plus" className="fs-15" /> Add New
            </Button>
          )}
        </div>

        <div className="d-flex align-items-center gap-2">
          {canWrite && (
            <Button
              variant="success"
              size="sm"
              className="d-flex align-items-center gap-1 fw-semibold px-3 py-2"
              onClick={handleSaveAll}
            >
              <Icon icon="save" className="fs-15" /> Save All Settings
            </Button>
          )}

          <OverlayTrigger
            placement="top"
            overlay={
              <Tooltip id="settings-options">
                Settings Options &amp; Export
              </Tooltip>
            }
          >
            <Button
              variant="primary"
              size="sm"
              className="btn-icon rounded-circle d-flex align-items-center justify-content-center"
            >
              <Icon icon="settings" className="fs-16" />
            </Button>
          </OverlayTrigger>
        </div>
      </div>

      {/* "+ Add New" Panel matching Image 2 OR Settings List matching Image 1 */}
      {isAdding ? (
        <Card className="mb-4 border shadow-sm">
          <CardBody className="p-4">
            <h6 className="fw-bold mb-3 d-flex align-items-center justify-content-between">
              <span>Create New Setting Item</span>
              <span
                className="text-primary fs-13 cursor-pointer"
                onClick={() => {
                  setIsAdding(false);
                  setIsKeyAutoGenerated(true);
                }}
              >
                <Icon icon="x" /> Close
              </span>
            </h6>
            <form onSubmit={handleAddSetting} noValidate>
              <Row className="g-3 align-items-start">
                <Col md={3}>
                  <FormLabel className="fs-12 text-muted fw-semibold mb-1">
                    Display Name <span className="text-danger">*</span>
                  </FormLabel>
                  <FormControl
                    type="text"
                    placeholder="Display Name"
                    isInvalid={Boolean(errors.displayName)}
                    value={newSetting.displayName}
                    onChange={(e) => {
                      const val = e.target.value;
                      const grp =
                        groupSearch.trim() || newSetting.group || "General";
                      const autoKey = isKeyAutoGenerated
                        ? generateAutoKey(val, grp)
                        : newSetting.key;
                      setNewSetting({
                        ...newSetting,
                        displayName: val,
                        key: autoKey,
                      });
                      if (errors.displayName)
                        setErrors((prev) => ({
                          ...prev,
                          displayName: undefined,
                        }));
                      if (isKeyAutoGenerated && errors.key)
                        setErrors((prev) => ({ ...prev, key: undefined }));
                    }}
                  />
                  {errors.displayName && (
                    <div className="text-danger fs-12 mt-1">
                      {errors.displayName}
                    </div>
                  )}
                </Col>

                <Col md={3}>
                  <FormLabel className="fs-12 text-muted fw-semibold mb-1">
                    Key <span className="text-danger">*</span>
                  </FormLabel>
                  <FormControl
                    type="text"
                    placeholder="Key (e.g. general.title)"
                    isInvalid={Boolean(errors.key)}
                    value={newSetting.key}
                    onChange={(e) => {
                      setNewSetting({ ...newSetting, key: e.target.value });
                      setIsKeyAutoGenerated(false);
                      if (errors.key)
                        setErrors((prev) => ({ ...prev, key: undefined }));
                    }}
                  />
                  {errors.key && (
                    <div className="text-danger fs-12 mt-1">{errors.key}</div>
                  )}
                </Col>

                <Col md={3}>
                  <FormLabel className="fs-12 text-muted fw-semibold mb-1">
                    Type <span className="text-danger">*</span>
                  </FormLabel>
                  <FormSelect
                    isInvalid={Boolean(errors.type)}
                    value={newSetting.type}
                    onChange={(e) => {
                      setNewSetting({
                        ...newSetting,
                        type: e.target.value as any,
                      });
                      if (errors.type)
                        setErrors((prev) => ({ ...prev, type: undefined }));
                    }}
                  >
                    <option value="">Choose Type...</option>
                    <option value="text">Text Input</option>
                    <option value="file">File / Image Upload</option>
                    <option value="textarea">Textarea / Code</option>
                    <option value="switch">Switch / Boolean</option>
                  </FormSelect>
                  {errors.type && (
                    <div className="text-danger fs-12 mt-1">{errors.type}</div>
                  )}
                </Col>

                {/* Searchable & Creatable Dropdown for Group */}
                <Col md={3} className="position-relative">
                  <FormLabel className="fs-12 text-muted fw-semibold mb-1">
                    Select Existing Group or Add New{" "}
                    <span className="text-danger">*</span>
                  </FormLabel>
                  <div className="input-group">
                    <FormControl
                      type="text"
                      placeholder="Search or enter new group..."
                      isInvalid={Boolean(errors.group)}
                      value={groupSearch}
                      onFocus={() => setShowGroupDropdown(true)}
                      onBlur={() =>
                        setTimeout(() => setShowGroupDropdown(false), 200)
                      }
                      onChange={(e) => {
                        const grp = e.target.value;
                        const autoKey = isKeyAutoGenerated
                          ? generateAutoKey(newSetting.displayName, grp)
                          : newSetting.key;
                        setGroupSearch(grp);
                        setNewSetting({
                          ...newSetting,
                          group: grp,
                          key: autoKey,
                        });
                        if (errors.group)
                          setErrors((prev) => ({ ...prev, group: undefined }));
                        if (isKeyAutoGenerated && errors.key)
                          setErrors((prev) => ({ ...prev, key: undefined }));
                        setShowGroupDropdown(true);
                      }}
                    />
                    <Button
                      variant="outline-secondary"
                      type="button"
                      className="d-flex align-items-center"
                      onClick={() => setShowGroupDropdown(!showGroupDropdown)}
                    >
                      <Icon icon="chevron-down" className="fs-14" />
                    </Button>
                  </div>
                  {errors.group && (
                    <div className="text-danger fs-12 mt-1">{errors.group}</div>
                  )}

                  {showGroupDropdown && (
                    <div
                      className="position-absolute start-0 end-0 mt-1 bg-white border rounded shadow py-1 z-3"
                      style={{
                        maxHeight: "220px",
                        overflowY: "auto",
                        zIndex: 1050,
                      }}
                    >
                      {/* Option to create a new group if text typed does not exist */}
                      {groupSearch.trim() && !exactGroupMatch && (
                        <div
                          className="dropdown-item py-2 px-3 cursor-pointer d-flex align-items-center justify-content-between text-primary fw-semibold bg-primary bg-opacity-10"
                          onMouseDown={() =>
                            handleSelectGroupOption(groupSearch.trim())
                          }
                        >
                          <span>
                            <Icon icon="plus" className="me-1" /> Add &quot;
                            {groupSearch.trim()}&quot; as new group
                          </span>
                          <Badge bg="primary" className="fs-11">
                            New Option
                          </Badge>
                        </div>
                      )}

                      {/* Existing Matching Groups */}
                      {matchingGroups.length === 0 &&
                        (!groupSearch.trim() || exactGroupMatch) && (
                          <div className="py-2 px-3 text-muted fs-13 text-center">
                            No matching groups found
                          </div>
                        )}

                      {matchingGroups.map((grp) => (
                        <div
                          key={grp}
                          className={`dropdown-item py-2 px-3 cursor-pointer d-flex align-items-center justify-content-between ${
                            groupSearch.trim().toLowerCase() ===
                            grp.toLowerCase()
                              ? "bg-light fw-semibold text-primary"
                              : "text-dark"
                          }`}
                          onMouseDown={() => handleSelectGroupOption(grp)}
                        >
                          <span>{grp}</span>
                          {groupSearch.trim().toLowerCase() ===
                            grp.toLowerCase() && (
                            <Icon icon="check" className="fs-14 text-primary" />
                          )}
                        </div>
                      ))}
                    </div>
                  )}
                </Col>

                {newSetting.type === "textarea" && (
                  <Col xs={12}>
                    <div className="border rounded bg-light p-2 mt-2 font-monospace fs-13">
                      <div className="d-flex">
                        <span className="text-muted pe-3 border-end user-select-none">
                          1
                        </span>
                        <textarea
                          className="form-control border-0 bg-transparent py-0 ps-3 shadow-none"
                          rows={3}
                          placeholder="Enter default code or content..."
                          value={newSetting.value}
                          onChange={(e) =>
                            setNewSetting({
                              ...newSetting,
                              value: e.target.value,
                            })
                          }
                        />
                      </div>
                    </div>
                  </Col>
                )}

                {newSetting.type === "file" && (
                  <Col xs={12} className="mt-2">
                    <div className="border rounded bg-light p-2 d-flex align-items-center gap-2">
                      <label className="btn btn-sm btn-outline-primary mb-0 cursor-pointer d-flex align-items-center gap-1">
                        <Icon icon="upload" className="fs-14" />
                        <span>Choose File</span>
                        <input
                          type="file"
                          className="d-none"
                          accept="image/*,.ico,.svg,.pdf"
                          onChange={async (e) => {
                            const file = e.target.files?.[0];
                            if (!file) return;
                            const localUrl = URL.createObjectURL(file);
                            setNewSetting((prev) => ({
                              ...prev,
                              value: localUrl,
                            }));
                            const formData = new FormData();
                            formData.append("file", file);
                            const token =
                              typeof window !== "undefined"
                                ? localStorage.getItem("token") ||
                                  sessionStorage.getItem("token")
                                : null;
                            const headers: HeadersInit = token
                              ? { Authorization: `Bearer ${token}` }
                              : {};
                            try {
                              let response = await fetch(
                                `${API_URL}/admin/settings/upload`,
                                { method: "POST", headers, body: formData },
                              );
                              if (!response.ok)
                                response = await fetch(
                                  `${API_URL}/settings/upload`,
                                  { method: "POST", headers, body: formData },
                                );
                              if (response.ok) {
                                const resData = await response.json();
                                const uploadedUrl =
                                  resData.url ||
                                  (resData.data && resData.data.url) ||
                                  "";
                                if (uploadedUrl)
                                  setNewSetting((prev) => ({
                                    ...prev,
                                    value: uploadedUrl,
                                  }));
                              }
                            } catch (err) {}
                          }}
                        />
                      </label>
                      <span className="text-muted fs-13 text-truncate">
                        {newSetting.value
                          ? newSetting.value
                          : "No file selected yet..."}
                      </span>
                    </div>
                  </Col>
                )}

                <Col xs={12} className="mt-3">
                  <Button
                    type="submit"
                    variant="primary"
                    className="px-4 fw-semibold"
                  >
                    Add Setting
                  </Button>
                </Col>
              </Row>
            </form>
          </CardBody>
        </Card>
      ) : (
        <div className="settings-list d-flex flex-column gap-3">
          {filteredSettings.length === 0 ? (
            <Card className="border text-center py-5">
              <CardBody>
                <Icon icon="sliders" className="fs-36 text-muted mb-2" />
                <h6 className="fw-semibold">No settings found in this group</h6>
                <p className="text-muted fs-13 mb-0">
                  Click &quot;+ Add New&quot; above to create a setting in{" "}
                  {activeGroup}.
                </p>
              </CardBody>
            </Card>
          ) : (
            filteredSettings.map((item) => (
              <Card key={item.id} className="border-light shadow-sm">
                <CardBody className="p-3">
                  {/* Header line of card: Title + red pill key badge + red X close button */}
                  <div className="d-flex align-items-center justify-content-between mb-2">
                    <div className="d-flex align-items-center gap-2 flex-wrap">
                      <span className="fw-bold fs-14 text-dark">
                        {item.displayName}
                      </span>
                      <Badge
                        bg="danger"
                        className="bg-opacity-10 text-danger fw-normal px-2 py-1 font-monospace fs-12"
                      >
                        {item.key}
                      </Badge>
                    </div>

                    {canDelete && (
                      <OverlayTrigger
                        placement="top"
                        overlay={
                          <Tooltip id={`del-${item.id}`}>
                            Delete Setting
                          </Tooltip>
                        }
                      >
                        <Button
                          variant="link"
                          className="p-0 text-danger text-opacity-75 border-0"
                          onClick={() => handleDeleteSetting(item.id)}
                        >
                          <Icon icon="x" className="fs-18" />
                        </Button>
                      </OverlayTrigger>
                    )}
                  </div>

                  {/* Input row + Group selector */}
                  <Row className="g-3 align-items-start">
                    <Col md={9} lg={10}>
                      {item.type === "text" && (
                        <FormControl
                          type="text"
                          value={item.value as string}
                          disabled={!canWrite}
                          onChange={(e) =>
                            handleUpdateValue(item.id, e.target.value)
                          }
                          className="bg-light-subtle"
                        />
                      )}

                      {item.type === "file" && (
                        <div>
                          <div className="input-group">
                            <label
                              className={`btn btn-light border mb-0 cursor-pointer d-flex align-items-center gap-1 ${!canWrite ? "disabled" : ""}`}
                            >
                              <Icon
                                icon="upload"
                                className="fs-14 text-primary"
                              />
                              <span className="fw-medium">Choose File</span>
                              <input
                                type="file"
                                className="d-none"
                                disabled={!canWrite}
                                accept=".jpg,.jpeg,.png,.webp,.svg,.ico,.pdf"
                                onChange={(e) => handleFileUpload(item.id, e)}
                              />
                            </label>
                            <FormControl
                              type="text"
                              placeholder="No file chosen or URL..."
                              value={
                                typeof item.value === "string" && item.value
                                  ? item.value
                                  : ""
                              }
                              disabled={!canWrite}
                              onChange={(e) =>
                                handleUpdateValue(item.id, e.target.value)
                              }
                              className="bg-light-subtle"
                            />
                          </div>
                          <div className="d-flex align-items-center justify-content-between mt-2 flex-wrap gap-2">
                            <span className="text-muted fs-12">
                              View Link:{" "}
                              {item.value || item.previewUrl ? (
                                <a
                                  href={
                                    (typeof item.value === "string"
                                      ? item.value
                                      : item.previewUrl) || "#"
                                  }
                                  target="_blank"
                                  rel="noreferrer"
                                  className="text-primary text-decoration-none fw-medium"
                                >
                                  {typeof item.value === "string"
                                    ? item.value.startsWith("blob:")
                                      ? "Preview Link"
                                      : item.value.split("/").pop() || "View Link"
                                    : "View Link"}
                                </a>
                              ) : (
                                <span>None</span>
                              )}
                            </span>
                          </div>

                          {(item.previewUrl ||
                            (typeof item.value === "string" &&
                              (item.value.match(
                                /\.(jpeg|jpg|png|gif|webp|svg|ico)$/i,
                              ) ||
                                item.value.startsWith("data:image") ||
                                item.value.startsWith("blob:") ||
                                item.value.includes("/images/") ||
                                item.value.includes("/uploads/")))) && (
                            <div className="mt-2">
                              <div
                                className="rounded-3 border p-1 d-inline-flex align-items-center justify-content-center bg-white shadow-sm"
                                style={{ width: "64px", height: "64px" }}
                              >
                                <img
                                  src={
                                    item.previewUrl ||
                                    (typeof item.value === "string"
                                      ? item.value
                                      : "")
                                  }
                                  alt={item.displayName}
                                  className="img-fluid rounded"
                                  style={{
                                    maxHeight: "56px",
                                    maxWidth: "56px",
                                    objectFit: "contain",
                                  }}
                                />
                              </div>
                            </div>
                          )}
                        </div>
                      )}

                      {item.type === "textarea" && (
                        <textarea
                          rows={2}
                          className="form-control bg-light-subtle"
                          value={item.value as string}
                          disabled={!canWrite}
                          onChange={(e) =>
                            handleUpdateValue(item.id, e.target.value)
                          }
                        />
                      )}

                      {item.type === "switch" && (
                        <div className="pt-1">
                          <FormCheck
                            type="switch"
                            id={`switch-${item.id}`}
                            label={item.value ? "Enabled" : "Disabled"}
                            checked={Boolean(item.value)}
                            disabled={!canWrite}
                            onChange={(e) =>
                              handleUpdateValue(item.id, e.target.checked)
                            }
                            className="fs-14 fw-semibold"
                          />
                        </div>
                      )}
                    </Col>

                    <Col md={3} lg={2}>
                      <FormSelect
                        value={item.group}
                        disabled={!canWrite}
                        onChange={(e) =>
                          handleUpdateGroup(item.id, e.target.value)
                        }
                        className="form-select-sm bg-light-subtle"
                      >
                        {groups.map((g) => (
                          <option key={g} value={g}>
                            {g}
                          </option>
                        ))}
                      </FormSelect>
                    </Col>
                  </Row>
                </CardBody>
              </Card>
            ))
          )}
        </div>
      )}
    </div>
  );
};

export default WebsiteSettingsContent;
